name: Test pwnvim configuration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       
      - name: Install Nix package manager
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install neovim config
        run: |
          nix develop --command nvim +q

      # - name: Show startuptime time
      #   run: |
      #     nix develop --command nvim --startuptime tmp.txt
      #     tail -n 1 tmp.txt
